language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - nightly
notifications:
  email: false
branches:
  only:
  - master
  - /v(\d+)\.(\d+)\.(\d+)/   
matrix:
  allow_failures:
  - julia: nightly
  fast_finish: true
after_success:
- julia -e 'cd(Pkg.dir("Classes")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
